### ISSUE TITLE
Do not use ReadObjectThreaded on scene objects!

### ISSUE THREAD

**Issue by 8secz-johndpope** [mmakhalaf/gesture-recognition-unity3d#1]
In  unity 2019 - 

I upgraded ActionRecognizer 

```c#
public class ActionRecognizer : MonoBehaviour
{
	public RawImage  costMatrixTexture;
```

but when I build I get error Do not use ReadObjectThreaded on scene objects!

any ideas?

**Comment by mmakhalaf** [comment]
This was a project I did in 2012 and haven't been current with Unity since, so I'm afraid I don't know, sorry.
