### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by msm1314zjq** [mmakhalaf/gesture-recognition-unity3d#2]
hello,Would you mind showing me your paper? I looked for it for a long time but I couldn't find it.

**Comment by mmakhalaf** [comment]
This was a little research mini-project for a module in my MSc, and hasn't resulted in a published paper.  [Here is](https://github.com/mmakhalaf/gesture-recognition-unity3d/files/5066580/report.pdf) the report though, I hope it helps.
